var num = 10;
console.log(typeof(num));
num = false;
console.log(num);
console.log(typeof(num));
num=" Jitendra Chauhan";
console.log(num);
console.log(typeof(num));
num=null;
console.log(num);
console.log(typeof(null));
num=" undefined";
console.log(num);
console.log(typeof(num));
